emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-aaz"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/CommunityTrainings.json"
  "@azure-tools/typespec-aaz":
    operation: "get-resources-operations"
    api-version: "2023-11-01"
    resources: ["/subscriptions/{}/resourcegroups/{}/providers/microsoft.community/communitytrainings/{}"]
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/../"
    output-file: "{output-folder-base}/OpenApiV3/{version}/assistants_generated.yaml"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
  disable:
    "@azure-tools/typespec-azure-resource-manager/arm-common-types-version": "New rule"
